
 The following SQL statements will be executed:

     CREATE TABLE composed (id INT AUTO_INCREMENT NOT NULL, challenge INT NOT NULL, points_amount INT NOT NULL, UNIQUE INDEX UNIQ_6CA7B389D7098951 (challenge), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
     CREATE TABLE composed_exercise (composed_id INT NOT NULL, exercise_id INT NOT NULL, INDEX IDX_EFAFD5EDFFF2E63 (composed_id), INDEX IDX_EFAFD5EDE934951A (exercise_id), PRIMARY KEY(composed_id, exercise_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
     CREATE TABLE exercise_state (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
     CREATE TABLE language (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
     CREATE TABLE participate (id INT AUTO_INCREMENT NOT NULL, user_points INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
     CREATE TABLE participate_user (participate_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_5203D6C95FE98FC0 (participate_id), INDEX IDX_5203D6C9A76ED395 (user_id), PRIMARY KEY(participate_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
     CREATE TABLE participate_challenge (participate_id INT NOT NULL, challenge_id INT NOT NULL, INDEX IDX_9D5C58E35FE98FC0 (participate_id), INDEX IDX_9D5C58E398A21AC6 (challenge_id), PRIMARY KEY(participate_id, challenge_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
     CREATE TABLE exercise (id INT AUTO_INCREMENT NOT NULL, user INT NOT NULL, exercisestate INT NOT NULL, difficulty INT NOT NULL, description LONGTEXT DEFAULT NULL, name VARCHAR(255) NOT NULL, folder_path VARCHAR(255) NOT NULL, submit_date DATETIME NOT NULL, approved_date DATETIME DEFAULT NULL, INDEX IDX_AEDAD51C8D93D649 (user), INDEX IDX_AEDAD51CA793C052 (exercisestate), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
     CREATE TABLE restricted (id INT AUTO_INCREMENT NOT NULL, exercise INT NOT NULL, UNIQUE INDEX UNIQ_C7CC8047AEDAD51C (exercise), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
     CREATE TABLE restricted_language (restricted_id INT NOT NULL, language_id INT NOT NULL, INDEX IDX_14830432BAC54862 (restricted_id), INDEX IDX_1483043282F1BAF4 (language_id), PRIMARY KEY(restricted_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
     CREATE TABLE constrained (id INT AUTO_INCREMENT NOT NULL, challenge INT NOT NULL, UNIQUE INDEX UNIQ_988EB062D7098951 (challenge), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
     CREATE TABLE constrained_language (constrained_id INT NOT NULL, language_id INT NOT NULL, INDEX IDX_77644ED1C3D7DA79 (constrained_id), INDEX IDX_77644ED182F1BAF4 (language_id), PRIMARY KEY(constrained_id, language_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
     CREATE TABLE challenge (id INT AUTO_INCREMENT NOT NULL, start_date DATETIME NOT NULL, end_date DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
     CREATE TABLE solving (id INT AUTO_INCREMENT NOT NULL, user INT NOT NULL, exercise INT NOT NULL, completed_test_amount INT NOT NULL, last_submitted_code LONGTEXT DEFAULT NULL, INDEX IDX_C4768F368D93D649 (user), INDEX IDX_C4768F36AEDAD51C (exercise), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
     CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(60) NOT NULL, last_name VARCHAR(60) NOT NULL, email VARCHAR(60) NOT NULL, join_date DATETIME NOT NULL, api_key VARCHAR(32) NOT NULL, UNIQUE INDEX UNIQ_8D93D649F85E0677 (username), UNIQUE INDEX UNIQ_8D93D649C912ED9D (api_key), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
     ALTER TABLE composed ADD CONSTRAINT FK_6CA7B389D7098951 FOREIGN KEY (challenge) REFERENCES challenge (id);
     ALTER TABLE composed_exercise ADD CONSTRAINT FK_EFAFD5EDFFF2E63 FOREIGN KEY (composed_id) REFERENCES composed (id) ON DELETE CASCADE;
     ALTER TABLE composed_exercise ADD CONSTRAINT FK_EFAFD5EDE934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id) ON DELETE CASCADE;
     ALTER TABLE participate_user ADD CONSTRAINT FK_5203D6C95FE98FC0 FOREIGN KEY (participate_id) REFERENCES participate (id) ON DELETE CASCADE;
     ALTER TABLE participate_user ADD CONSTRAINT FK_5203D6C9A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;
     ALTER TABLE participate_challenge ADD CONSTRAINT FK_9D5C58E35FE98FC0 FOREIGN KEY (participate_id) REFERENCES participate (id) ON DELETE CASCADE;
     ALTER TABLE participate_challenge ADD CONSTRAINT FK_9D5C58E398A21AC6 FOREIGN KEY (challenge_id) REFERENCES challenge (id) ON DELETE CASCADE;
     ALTER TABLE exercise ADD CONSTRAINT FK_AEDAD51C8D93D649 FOREIGN KEY (user) REFERENCES user (id) ON DELETE CASCADE;
     ALTER TABLE exercise ADD CONSTRAINT FK_AEDAD51CA793C052 FOREIGN KEY (exercisestate) REFERENCES exercise_state (id);
     ALTER TABLE restricted ADD CONSTRAINT FK_C7CC8047AEDAD51C FOREIGN KEY (exercise) REFERENCES exercise (id);
     ALTER TABLE restricted_language ADD CONSTRAINT FK_14830432BAC54862 FOREIGN KEY (restricted_id) REFERENCES restricted (id) ON DELETE CASCADE;
     ALTER TABLE restricted_language ADD CONSTRAINT FK_1483043282F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id) ON DELETE CASCADE;
     ALTER TABLE constrained ADD CONSTRAINT FK_988EB062D7098951 FOREIGN KEY (challenge) REFERENCES challenge (id);
     ALTER TABLE constrained_language ADD CONSTRAINT FK_77644ED1C3D7DA79 FOREIGN KEY (constrained_id) REFERENCES constrained (id) ON DELETE CASCADE;
     ALTER TABLE constrained_language ADD CONSTRAINT FK_77644ED182F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id) ON DELETE CASCADE;
     ALTER TABLE solving ADD CONSTRAINT FK_C4768F368D93D649 FOREIGN KEY (user) REFERENCES user (id) ON DELETE CASCADE;
     ALTER TABLE solving ADD CONSTRAINT FK_C4768F36AEDAD51C FOREIGN KEY (exercise) REFERENCES exercise (id);
